### ISSUE TITLE
KeyError: 'HOME' with drive.py

### ISSUE THREAD

**Issue by ghost** [larsks/gitdriver#7]
I have created an OAuth client id and secret along with gd.conf, but I get this error:

```
Traceback (most recent call last):
  File "gitdriver.py", line 72, in <module>
    main()
  File "gitdriver.py", line 34, in main
    scopes=[DRIVE_RW_SCOPE],
  File "C:\Users\EnragedViper\Downloads\gitdriver-master\gitdriver-master\drive.py", line 42, in __init__
    credentials = os.path.join(os.environ['HOME'], '.googledrive')
  File "C:\Python27\lib\os.py", line 425, in __getitem__
    return self.data[key.upper()]
KeyError: 'HOME'
```

**Comment by larsks** [comment]
Note that I haven't really touched this code since 2013, so no guarantees that it's even functional.

The code largely assumes a Linux environment, in which the `HOME` environment is pretty much guaranteed to exist.  The easiest solution is probably to `HOME` in your environment to a useful directory.  If you wanted to modify the code, you would probably want to add a command line option for specifying a location to store the google drive credentials, and then modify the call to `GoogleDrive` to include a `credentials` parameter.

**Comment by ghost** [comment]
Thanks. For future reference, for Windows 'USERPROFILE' is the environment variable.
